apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-service
  labels:
    app: microservices-poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservices-poc
  template:
    metadata:
      labels:
        app: microservices-poc
    spec:
      containers:
        - name: microservices-poc
          image: sriharipriya/microservices-poc:${{ github.run_number }}

          ports: 
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: microservices-poc-loadbalancer-service
  labels:
    app: microservices-poc
spec:
  type: LoadBalancer
  selector:
    app: microservices-poc
  ports:
    - port: 8080
      targetPort: 8080
